Task/bnpl
101digital/adb-loan-origination-component pull request #18
Opened 2023-03-14 12:38 UTC by talha-101digital

### Why

Please give a short description why these code changes are being made, by replacing this line.

Link to Jira ticket: <place here>

### ToDo

- [ ]
- [ ]
- [ ]

If this is a `Draft:` or `WIP:` PR, please describe still needed actions, else delete section

2023-03-15 00:59 UTC, sharmal33 requested changes
plz redo this

2023-03-15 00:59 UTC, sharmal33 commented on index.d.ts
> +export { default as CashSelectAmountComponent } from './src/components/cash-advance-selector';
why changed the cash-advance files

2023-03-15 00:59 UTC, sharmal33 commented on index.js
> +export { default as CashSelectAmountComponent } from './src/components/cash-advance-selector';
why you change the cash-advance files

2023-03-15 00:59 UTC, sharmal33 commented on src/components/bnlp-hub.tsx
> +                  <Text style={styles.txtDis}>28 Nov 2022</Text>
why it's hardcoded ?

2023-03-15 00:59 UTC, sharmal33 commented on src/components/bnlp-hub.tsx
> +        account.map((item) => (
create a child component for this and import it

2023-03-15 00:59 UTC, sharmal33 commented on src/components/bnlp-hub.tsx
> +          </Text>
move this into translation file

2023-03-15 00:59 UTC, sharmal33 commented on src/components/bnpl-application-reviewed.tsx
> +      },
this is wrong

2023-03-15 00:59 UTC, sharmal33 commented on src/components/bnpl-application-reviewed.tsx
> +      },
this is wrong

2023-03-15 00:59 UTC, sharmal33 commented on src/components/bnpl-application-reviewed.tsx
> +      },
plz check this with tung this payload is wrong

2023-03-15 00:59 UTC, sharmal33 commented on src/components/bnpl-approved.tsx
> +        requestedPeriod: data?.duration.toString(),
this payload is wrong

2023-03-15 00:59 UTC, sharmal33 commented on src/components/bnpl-approved.tsx
> +              </Text>
why is hardcoded ?

2023-03-15 00:59 UTC, sharmal33 commented on src/components/bnpl-approved.tsx
> +          <Text style={styles.txtCopy}>
plz redo this

2023-03-15 00:59 UTC, sharmal33 commented on src/components/bnpl-confirm.tsx
> +      bankId: bankId === undefined ? 'FNXSMYNB' : bankId,
wrong

2023-03-15 00:59 UTC, sharmal33 commented on src/components/bnpl-confirm.tsx
> +        customKey: 'SubProcessStep',
wrong

2023-03-15 00:59 UTC, sharmal33 commented on src/components/bnpl-confirm.tsx
> +          {i18n?.t('loan-origination-component.disbursement-account')}
plz redo this

2023-03-15 00:59 UTC, sharmal33 commented on src/components/cash-advance-application.tsx
> +import React, { useContext, useEffect, useState } from 'react';
why you update this file

2023-03-15 00:59 UTC, sharmal33 commented on src/components/cash-advance-selector.tsx
> +import React, { useContext, useEffect, useState } from 'react';
why you are updating this file.

2023-03-15 00:59 UTC, sharmal33 commented on src/components/review-final.tsx
>        console.log('EMPLOYMENT-SECTOR');
remove this

2023-03-15 00:59 UTC, sharmal33 commented on src/components/review-final.tsx
>      }
why you are hardcode this

2023-03-15 00:59 UTC, sharmal33 commented on src/contexts/loan-component-context.tsx
> +      console.log('e', JSON.stringify(e?.message));
remove all longs

2023-03-21 08:46 UTC, talha-101digital commented on src/components/review-final.tsx
>      }
for checking which model i need to open

2023-03-23 06:37 UTC, usamabutt101 commented on src/components/bnlp-hub.tsx
> +        application.map((item) => (
Try to use the FlatList to get a better UI experience if not then please extract the "key" from the map and pass it as a "key" prop into the parent View tag in the return of "map". Otherwise, there will be so many warning errors will appear in the debug console.

application.map((item) => (
         <View key={key}></View>
)

2023-03-23 06:37 UTC, usamabutt101 commented on src/components/bnlp-hub.tsx
>  const EligibleTransaction = (props: any) => {
These card components or widgets should be in a separate component file to clean the main component.

2023-03-23 06:37 UTC, usamabutt101 commented on src/components/bnlp-hub.tsx
> +const BnplAccounts = (props: any) => {
These card components or widgets should be in a separate component file to clean the main component.

2023-04-04 03:09 UTC, closed without merging